// Actions > Error
const SHOW_ERROR = 'SHOW_ERROR';
const HIDE_ERROR = 'HIDE_ERROR';

// Actions > Login
const GET_LOGIN_REQUEST = 'GET_LOGIN_REQUEST';
const GET_LOGIN_SUCCESS = 'GET_LOGIN_SUCCESS';
const GET_LOGIN_ERROR = 'GET_LOGIN_ERROR';

// Actions > Logout
const GET_LOGOUT_REQUEST = 'GET_LOGOUT_REQUEST';
const GET_LOGOUT_SUCCESS = 'GET_LOGOUT_SUCCESS';
const GET_LOGOUT_ERROR = 'GET_LOGOUT_ERROR';

export {
    SHOW_ERROR,
    HIDE_ERROR,
    GET_LOGIN_REQUEST,
    GET_LOGIN_SUCCESS,
    GET_LOGIN_ERROR,
    GET_LOGOUT_REQUEST,
    GET_LOGOUT_SUCCESS,
    GET_LOGOUT_ERROR,
};
